export type MapGrenade = {
    steamid: string,
    team: 'CT' | 'TERRORIST',
    grenade_type: string,
    start_x: number,
    start_y: number,
    start_z: number,
    end_x: number,
    end_y: number,
    end_z: number,
    start_time: number,
    end_time: number,
}

export type MapKill = {
    map_name: string,
    attacker_steamid: string | null,
    victim_steamid: string,
    attacker_team: 'CT' | 'TERRORIST' | null,
    victim_team: 'CT' | 'TERRORIST',
    attacker_this_team: boolean | null,
    victim_this_team: boolean,
    weapon: string,
    time: number,
    plant_time: number | null,
    attacker_x: number | null,
    attacker_y: number | null,
    attacker_z: number | null,
    victim_x: number,
    victim_y: number,
    victim_z: number,
    round_type: 'pistol' | 'eco' | 'buy',
    num_a: number,
    num_mid: number,
    num_b: number,
}

export type MapPlant = {
    map_name: string,
    site: "A" | "B",
    x: number,
    y: number,
    z: number,
    round_type: 'pistol' | 'eco' | 'buy',
    num_a: number,
    num_mid: number,
    num_b: number,
}
